spring:
  application:
    name: BetterTapeBot
  profiles:
    active: secret
  datasource:
    url: jdbc:postgresql://localhost:5432/tapebot
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
better-tape-bot:
  input-validation:
    username: "^[A-Za-z0-9+_.-]{2,255}$"
    pin: "^[0-9]{4}$"
  subscription:
    countsAsYes:
      - "ja"
      - "j"
      - "yes"
      - "y"
      - "true"
    countsAsNo:
      - "nein"
      - "n"
      - "no"
      - "n"
      - "false"
  telegram:
    token: "SECRET"