spring:
  application:
    name: BetterTapeBot
  profiles:
    active: secret
  datasource:
    url: jdbc:postgresql://localhost:5432/tapebot
    username: postgres
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
better-tape-bot:
  subscription:
    countsAsYes:
      - "ja"
      - "j"
      - "yes"
      - "y"
      - "true"
    countsAsNo:
      - "nein"
      - "n"
      - "no"
      - "n"
      - "false"
  telegram:
    token: "SECRET"