spring:
  application:
    name: BetterTapeBot
  datasource:
    url: jdbc:postgresql://BetterTapeBotDb:5432/bettertapebot
    username: changeme_app_user
    password: changeme_app_password
  liquibase:
    url: jdbc:postgresql://BetterTapeBotDb:5432/bettertapebot
    username: changeme_migration_user
    password: changeme_migration_password
  jpa:
    hibernate:
      ddl-auto: validate
better-tape-bot:
  subscription:
    countsAsYes:
      - "ja"
      - "j"
      - "yes"
      - "y"
    countsAsNo:
      - "nein"
      - "n"
      - "no"